name: Deploy NestJS Docker App to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d \
              --name ${{ github.event.repository.name }} \
              --network my_network \
              -p 4200:80 \
              -e EMAIL_SERVER_URL=http://nestjs-email-service:3000/email/send \
              sony2k20/${{ github.event.repository.name }}:latest
