name: Build Angular App and Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # https://github.com/npm/cli/issues/4828
      - name: Workaround for arm - remove package-lock.json
        run: rm -f package-lock.json

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration=development

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag sony2k20/ng-web-portfolio:latest \
            --tag sony2k20/ng-web-portfolio:${{ steps.vars.outputs.SHORT_SHA }} \
            --push .

  update-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the source repo
        uses: actions/checkout@v3

      - name: Get short SHA
        id: vars
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Clone Target Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://${{ secrets.COMMIT_TO_REPO_TOKEN }}@github.com/Sony2k20/gitops-deployments.git target-repo

      - name: Update image tag with short SHA
        run: |
          cd target-repo
          SHORT_SHA=${{ steps.vars.outputs.SHORT_SHA }}
          sed -i "s/tag:.*/tag: $SHORT_SHA/" app-of-apps/apps/ng-web-blog.yaml

      - name: Commit and Push Changes
        run: |
          cd target-repo
          git add apps/ng-web-blog.yaml
          git commit -m "Update ng-web-blog to version ${{ steps.vars.outputs.SHORT_SHA }}"
          git push origin master
